### ISSUE TITLE
pinMode doesn't actually do any i2c operation

### ISSUE THREAD

**Issue by ramarro123** [bodoba/PCF8574#1]
hi,

i need to set a pin in input mode, but looking at code, the actual i2c transaction it's done on write/read procedure, using mode as a bitmask.

it's that expected?

if i set input, and connect pin -> vcc i get extremely overhead, after a read, the pin get configured correctly and the chip start to cool down :)

i can of course do a dummy read  when i do the set, but it's still sub optimal, and at least for me  not expected. shouldn't it be do an empty read or something like that to properly set the mode?

**Comment by bodoba** [comment]
Hello,

thanks for having a look at my code :)

the HW manual said before reading the pin shall be set to high. So the read8 routing first sends high bits for all pins where read mode is set prior to reading the actual values. 

hth
BB
