### ISSUE TITLE
question about pin mode

### ISSUE THREAD

**Issue by ramarro123** [bodoba/PCF8574#2]
@bodoba

i read from code that
```

void PCF8574::pinMode(uint8_t pin, int mode) {
    if (pin >=1 && pin <= 8) {
```

and
```

int PCF8574::pinMode(uint8_t pin) {
    int pinmode = -1;
    if (pin >=0 && pin <= 7) {
```

check pin range in different way
it's pin range from 0 to 7 or 1 to 8?

in your example you use pinMode(0,OUTPUT) that return error = 5, so your examples doesn't seems to be correct i think, can you double check what you mean with the 2 different range?

randomly guessing, the 0-7 it's the correct one :)

**Comment by bodoba** [comment]
Hi,

you are right, this is a bug. Strange that it didn't bite me until now...

Regards,
BB
